---
  version: "3.8"
  services:
    rabbitmq:
      image: rabbitmq:3.8-management
      container_name: rabbitmq
      ports:
        - "15671:15671"
        - "15672:15672"
        - "5671:5671"
        - "5672:5672"
        - "25672:25672"
      volumes:
        - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq.conf:ro
      # - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    jaegar:
      image: jaegertracing/all-in-one
      container_name: jaeger
      ports:
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "16686:16686"
        - "14268:14268"
        - "14250:14250"
    otel:
      image: otel/opentelemetry-collector-contrib:latest
      container_name: otel
      command:
        - "/otelcontribcol"
        - "--config=/etc/otel/config.yaml"
        - "--mem-ballast-size-mib=683"
      ports:
        - "55680:55680"
        - "55679:55679"
        - "55678:55678"
        - "13133:13133"
        - "8888:8888"
        - "8889:8889"
      volumes:
        - ./otel/otel_collector_config.yaml:/etc/otel/config.yaml:ro
    # producer:
    #   image: producer:latest
    #   container_name: producder
    #   network_mode: host
    #   ports:
    #     - "3333:3333"
    #   # links:
    #   #   - rabbitmq
    #   depends_on:
    #     - rabbitmq