receivers:
  otlp: 
    protocols:
      grpc:
      http:
processors:
  batch:
  memory_limiter:
    # Same as --mem-ballast-size-mib CLI argument
    ballast_size_mib: 683
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
extensions:
  health_check: {}
  zpages: 
    endpoint: :55679
exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 5
service:
  extensions: [health_check, zpages]
  pipelines:
    traces/1:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]